# Standard Header
std_msgs/Header header

# Skeleton joints indices
#              10
#                \
#                 9
#                /
#       11-------8-------14
#       |        |       |
#       |        |       |
#       12       7       15
#       |        |       |
#       |        |       |
#       13   4---0---1   16
#            |       |
#            |       |
#            |       |
#            5       2
#            |       |
#            |       |
#            |       |
#            6       3
zed_interfaces/Keypoint3D[17] keypoints
